title: Miki Aso (Miki Ido)

description: |
Master student in Seismology
1-711 Department of Earth and Planetary Science
Graduate School of Science, The University of Tokyo

emails:
mainaddress: miki.aso@eps.s.u-tokyo.ac.jp
subaddress: miki.seis.aso@gmail.com

tel: +81 03-5841-4652

google_analytics:

theme: jekyll-theme-minimal
