title: Miki Aso (Miki Ido)

description:
  test
  Master student in Seismology
  <br>  
  1-711 Department of Earth and Planetary Science<br> 
  Graduate School of Science<br>
  The University of Tokyo<br>  
  <br>  
  miki.aso@eps.s.u-tokyo.ac.jp<br>    
  +81 03-5841-4652<br>   

test: test
#google_analytics:

theme: jekyll-theme-minimal




